# Page settings

baseURL = ""
relativeURLs = "True"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Vatsal Mehra"
    description = "Vatsal's Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Vatsal Mehra"
        tagline = "Bioinformatician and Software Developer"
        avatar = "mypic.jpg"







    [params.contact]
        enable = true
        location = "Hyderabad, India"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:mehra.vatsal@gmail.com"
        text = "mehra.vatsal@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.vatsalmehra.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Full Stack"
        [[params.skills.list.items]]
        details = "JavaScript/VueJS"
        [[params.skills.list.items]]
        details = "Python/Flask"
        [[params.skills.list.items]]
        details = "HTML5/CSS/Bootstrap/Jquery"
        [[params.skills.list.items]]
        details = "d3 (data driven documents)"
        [[params.skills.list.items]]
        details = "Node.js/ExpressJS"
        [[params.skills.list.items]]
        details = "MySQL/Redis/MongoDB"
        [[params.skills.list.items]]
        details = "Docker/Kubernetes"
        [[params.skills.list.items]]
        details = "REST/GraphQL API"
        [[params.skills.list.items]]
        details = "R"
        [[params.skills.list.items]]
        details = "Shell Scripting/Awk/Sed"
        [[params.skills.list.items]]
        details = "Git/Mercurial"
        [[params.skills.list.items]]
        details = "Nginx/Apache"

        [[params.skills.list]]
        title = "2D/3D Visualization"
        [[params.skills.list.items]]
        details = "d3.js/Observable/Vega"
        [[params.skills.list.items]]
        details = "Plotly/ggplot"
        [[params.skills.list.items]]
        details = "Three.js"

        [[params.skills.list]]
        title = "Bioinformatics/Machine Learning"
        [[params.skills.list.items]]
        details = "NGS pipelines (DNA-Seq, RNA-Seq, ATAC-Seq)"
        [[params.skills.list.items]]
        details = "Biopython"
        [[params.skills.list.items]]
        details = "Bioconductor"
        [[params.skills.list.items]]
        details = "Scikit-learn"







    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MS in Bioinformatics"
        university = "Marquette University"
        dates = "2014 - 2016"
        [[params.education.list]]
        degree = "B.Tech Computer Engineering"
        university = "NMIMS"
        dates = "2006 - 2010"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Science Communication"
        [[params.interests.list]]
        name = "Writing Nonfiction"
        [[params.interests.list]]
        name = "Podcasting"
        [[params.interests.list]]
        name = "Teaching Rationality"
        [[params.interests.list]]
        name = "Electronic Music Production"








    [params.summary]
        enable = true
        text = """Bioinformatician and a Software Developer with over 10 years of experience specializing in NGS pipelines, web development and data visualization. Skilled at delivering interactive tools for researchers, that provide novel insights in healthcare sector and biomedical sciences. Adept at learning new technologies autodidactically and flexible with different tech stacks. Loves [writing](http://rdbcasillas.github.io), [podcasting](https://open.spotify.com/show/79oICYy7ndxZIrQQWunirp) and [teaching rationality](https://year-one.hyperlink.academy/courses/introduction-to-applied-rationality/54).
        Occassionally, I also work with people directly to help with their personal and professional issues using numerous [instrumental rationality](https://www.lesswrong.com/posts/RcZCwxFiZzE6X7nsv/what-do-we-mean-by-rationality-1) techniques and frameworks (see projects section below for an overview of my public work). If you are interested in a coaching/career counselling session, please schedule a spot [here](https://calendly.com/vatsalmehra/60-min-chat)."""








    [params.experience]
        enable = true

	[[params.experience.list]]
        title = "Product Manager"
        dates = "Nov 2022 - Present"
        company = "Indx.Ai"
        details = "Building the iCare platform for oncologists to help them understand mutational profile of their patients and suggest appropriate therapy for cancer treatment."
        [[params.experience.list.items]]
        details = "Spearheading a team of software developers and bioinformaticians across multiple smaller projects within iCare."
        [[params.experience.list.items]]
        details = "Designing interactive user interfaces and robust bioinformatics pipelines for flagship products like OncoDx and OncoPredikt."


	[[params.experience.list]]
        title = "Data Scientist"
        dates = "Aug 2021 - Present"
        company = "Indx.Ai"
        details = "Building a webapp that discovers/annotates rare mutations in cancer patients and provides an interactive UI for oncologists to track patients and discover appropriate treatments."

        [[params.experience.list]]
        title = "Bioinformatician"
        dates = "Dec 2018 - Jan 2021"
        company = "Marquette University"
        details = "As the solo developer for a lab trying to cure spinal cord injury, I designed and developed multiple bioinformatics piplines and web tools that provide novel insights in genetic and epigenetic regulation behind axon growth. "
        [[params.experience.list.items]]
        details = "Developed bioinformatics pipelines that discovered novel transcription factor combinations regulating axon growth."
        [[params.experience.list.items]]
        details = "Created a web tool that allows scientists to visualize ATAC-Seq, RNA-seq and Histone Chip-Seq datasets across different time points in development of mice."
        [[params.experience.list.items]]
        details = "Developed a website that visualizes and quantifies supra spinal neurons with projections to the cervical, thoracic and lumbar segments."

        [[params.experience.list]]
        title = "Programmer Analyst"
        dates = "April 2018 - July 2018"
        company = "Medical College of Wisconsin"
        details = "Developed a tool for the Rat Genome database that provides a unique way to seamlessly visualize and perform set operations on lists of genes."

        [[params.experience.list]]
        title = "Bioinformatics Support Analyst"
        dates = "Oct 2016 - March 2018"
        company = "Blood Center of Wisconsin"
        details = ""
        [[params.experience.list.items]]
        details = "Developed web-based tools using the Flask framework, that automate and simplify the Bioinformatics workflow of Molecular Diagnostics Lab"
        [[params.experience.list.items]]
        details = "Human clinical genomics - Monitored NGS workflow, develop variant calling and variant annotation pipelines"
        [[params.experience.list.items]]
        details = "Designed and created an interactive web tool VIRAS, that provides a graphical view to analyze nucleotide mismatches between patients 10.1016/j.bbmt.2018.12.006 "
        [[params.experience.list.items]]
        details = "Developed data visualization tools using d3.js to help investigators analyze NGS workflow and patient report data"

        [[params.experience.list]]
        title = "Consultant Bioinformatician"
        dates = "May 2016 - Oct 2016"
        company = "Marquette Univeristy"
        details = "Developed custom shell scripts that automate RNA-Seq, and ChIP-Seq workflows"

        [[params.experience.list]]
        title = "Research Assistant"
        dates = "Aug 2015 - May 2016"
        company = "Marqutte University"
        details = "Designed & developed SNPredict, a tool that predicts rare somatic variants using multiple machine learning training algorithms like kNN & LinearSVC"

        [[params.experience.list]]
        title = "Software Enginner"
        dates = "Aug 2010 - Nov 2013"
        company = "Tech Mahindra, India"
        details = "Lead production support duties. Designed, coded and maintained Bash shell scripts to automate tasks for checking and updating status of AT&T servers."


    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "<a href='https://mousebraindev.com'>Mouse Brain Development DB</a>"
        meta = "Open Source"
        tagline = "Interactive visualizations to gain novel insights from time series NGS experiments on murine whole cortex"

        [[params.projects.list]]
        title = "<a href='https://3dmousebrain.com'>3d mouse brain</a>"
        meta = "Open Source"
        tagline = "3d visualization and quantification of supra spinal neurons with projections to the cervical, thoracic and lumbar segments."


        [[params.projects.list]]
        title = "<a href='stupefied-kepler-c3f8f3.netlify.app'>Teach Me A Bias</a>"
        meta = "Under Active Development"
        tagline = "A place to learn about different cognitive biases and how to overcome them."

        [[params.projects.list]]
        title = "<a href='https://open.spotify.com/show/79oICYy7ndxZIrQQWunirp'>Cerebral podcast</a>"
        meta = "Inactive"
        tagline = "A podcast that discusses human biases to better understand and improve human thinking/decision making"

        [[params.projects.list]]
        title = "<a href='https://hyperlink.academy/courses/introduction-to-applied-rationality/54'>Introduction To Applied Rationality</a>"
        meta = "Course"
        tagline = "A course/club designed for exploring different frameworks and techniques to achieve what we most want, given the physical and mental resources available to us."


        [[params.projects.list]]
        title = "Hyderabad Rationality Meetup"
        meta = "Meetup"
        tagline = "A bi-weekly meetup that explores the depths of rational thinking with a focus on systematically improving epistemic and instrumental rationality skills. <a href='https://www.lesswrong.com/posts/RcZCwxFiZzE6X7nsv/what-do-we-mean-by-rationality-1' target='_blank'>See here</a> for a definition of rationality we like to work with."









    [params.information]
        enable = true

        [[params.information.list]]
        title = ""
        [[params.information.list.items]]
        details = "2022 · [Brain-wide analysis of the supraspinal connectome reveals anatomical correlates to functional recovery after spinal injury](https://elifesciences.org/articles/76254) ***eLife***"
        [[params.information.list.items]]
        details = "2021 · [Co-occupancy identifies transcription factor co-operation for axon growth](https://www.nature.com/articles/s41467-021-22828-3) ***Nature Communications***"
        [[params.information.list.items]]
        details = "2018 · [Developmental chromatin restriction of pro-growth gene networks acts as an epigenetic barrier to axon regeneration in cortical neurons](https://www.biorxiv.org/content/10.1101/259408v1) ***Developmental Neurobiology***"
        [[params.information.list.items]]
        details = "2018 · [KLF6 and STAT3 co-occupy regulatory DNA and functionally synergize to promote axon growth in CNS neurons](https://www.nature.com/articles/s41598-018-31101-5) ***Scientific Reports***"
        [[params.information.list.items]]
        details = "2018 · [Direct HLA Genetic Comparisons Identify Highly Matched Unrelated Donor-Recipient Pairs with Improved Transplantation Outcome](https://pubmed.ncbi.nlm.nih.gov/30537549/) ***Biology of Blood and Marrow Transplantation***"
        [[params.information.list]]
        title = "Other Academic Interests"
        details = "Rationality, Educational Psychology, Effective Altruism, Evolutionary Biology, Cognitive Science"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/rdbcasillas"
        title = "rdbcasillas"
#        [[params.social.list]]
#        icon = "fab fa-linkedin"
#        url = "//linkedin.com/in/username"
#        title = "username"
#        [[params.social.list]]
#        icon = "fab fa-twitter-square"
#        url = "//twitter.com/username"
#        title = "@username"

    [params.footer]
        copyright = ""
